### ISSUE TITLE
Missing change to variable preventing expected behavior

### ISSUE THREAD

**Issue by schmittcw** [duosecurity/duo_coldfusion#7]
Line 135 of DuoWeb.cfc still references "cookie" instead of "Mycookie".

With that, the parseVals function throws an exception, but since it's called in a try/catch, the error is never seen. But any otherwise valid call to verifyResponse will return an empty string because of the thrown exception, thus preventing the expected result of a username on validation.

**Comment by AaronAtDuo** [comment]
@schmittcw Thanks for the heads up.  Is this something you could submit a PR for?  I'm nowhere close to being a CF dev, so if possible I'd prefer someone who knows what they are doing to fix this.

**Comment by schmittcw** [comment]
Done.

**Comment by AaronAtDuo** [comment]
Fixed by https://github.com/duosecurity/duo_coldfusion/pull/8.  Thanks so much!
